### ISSUE TITLE
Implement blogger/ghost importer

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#1]
This can be developed on top of JSON output of https://github.com/bebraw/blogger2ghost . Just need to convert that JSON to Markdown with suitable YAML headmatter.

**Comment by eldh** [comment]
Good idea. I suppose using commonmark to convert to markdown, and then just smacking the rest (at least the relevant parts) into the frontmatter. You might want to have an option clean the data, so that some keys are changed or filtered.

**Comment by bebraw** [comment]
Here's an example of [data you get out of the converter](https://gist.github.com/bebraw/02aff70944175473249e).

We should specify mapping for the data. As you can see there's a lot more data than in YAML headmatter at the moment. I think it would be a good idea to split date (created, published, updated?). If a post doesn't have published date, you can probably consider it a draft and exclude it of output.

I am a bit unsure about `headerImage`. If a post has images, maybe the first one could be picked. Is there a better heuristic? What if the image happens to be too small? Does the size matter?

`preview` is another one as the data is missing that. Maybe it could be just n first words out of the content? This rule could be configurable.

Tags are quite simple. I guess in this case you would just generate a list of tag names per post. If you want to make this more flexible, ids (can be slug, no number needed) can be used instead. That would be a good move as it would allow i18n over longer term.

Routing is one extra thing to worry about although it sounds like a separate issue. It would be good if my original blog links would still work (reroute to new ones). I guess this might mean I would need to generate an extra file for you with the mappings. How does that sound?

**Comment by eldh** [comment]
I think providing a barebones default mapping would be good, but being able to change/add to that mapping would be nice.

Antwar, at its core, only cares about two things in the .md files, the title and the content. The rest depends on what the theme (in this case Post.coffee and its sub-components) uses. And everything in the forntmatter part will be available through the PathsMixin. `headerImage`, for example, is just an optional field that's only relevant for this theme.

Yes, routing is an issue. now we generate the url from the file name, but we could look in the frontmatter also. Still, a mapping table to do 301 redirects is probably what you want to do. I son't really know how that works though. Putting the original url in the frontmatter should give us everything we need  I suppose.

**Comment by bebraw** [comment]
> Antwar, at its core, only cares about two things in the .md files, the title and the content. The rest depends on what the theme (in this case Post.coffee and its sub-components) uses. And everything in the forntmatter part will be available through the PathsMixin. headerImage, for example, is just an optional field that's only relevant for this theme.

Ok. I guess `headerImage` related logic, if needed, could be pushed to some plugin. I see now that the basic importer can be very simple.

The same idea applies to `tags` so that as well goes beyond the basic requirement.

Images are going to be bit of a problem. I would rather host them myself in the repository. I suppose this should go to a plugin that goes through the urls, fetches data and replaces the urls with the correct reference. Finally you should just commit that to the repo and off you go.

> Yes, routing is an issue. now we generate the url from the file name, but we could look in the frontmatter also. Still, a mapping table to do 301 redirects is probably what you want to do. I son't really know how that works though. Putting the original url in the frontmatter should give us everything we need I suppose.

What if there was a transformation function that would take post metadata as an input and output url(s)? You could generate whatever slugs you need or more complicated structures even and define redirects here. Basic idea:

```javascript
// basic
function basicUrlify(post) {
    return post.category + '/' + slugify(post.title);
}

// multiple urls per post
function multipleUrlify(post) {
    return [post.category + '/' + slugify(post.title), dateify(post.date) + '/' + slugify(post.title)];
}

// redirect
function redirectUrlify(post) {
    var to = dateify(post.date) + '/' + slugify(post.title);

    return [
        {
            from: post.category + '/' + slugify(post.title),
            to: to,
        },
        to,
    ];
}
```

As you can see, this could be a good extension point and it gives you a lot of control over the shape of urls.

**Comment by eldh** [comment]
Looks good!

**Comment by bebraw** [comment]
Can you provide a minimum spec for the mapping (ie. which fields should I generate)? I could try to whip up something.

I'll open a separate issue for that url thing.

**Comment by eldh** [comment]
The way it looks like right now is like this:

YYYY-MM-DD-[url].md

```
---
title: [title]
date: [YYYY-MM-DD]
---
[content]
```

You could also put the url in the frontMatter and add a line in `paths.coffee -> allPosts()` to check for the url there, I suppose.

Is that enough to get you started?

**Comment by bebraw** [comment]
Yeah, I'll do a quick stab at it in a separate repo. The tool will look like this: `ghost2antwar < inputDirectory > outputDirectory`.

I'm not sure about that `paths.coffee -> allPosts()` bit but maybe you can deal with that. The basic converter should give you some data to play with.

Ghost can import Wordpress too so you get a route from Wordpress to antwar too.

**Comment by eldh** [comment]
should I create an org for antwar and add you as a maintainer? Then we can keep all the repos there?


/æ

**Comment by bebraw** [comment]
> should I create an org for antwar and add you as a maintainer? Then we can keep all the repos there?

Sounds good!

**Comment by eldh** [comment]
damnit, antwar is taken...


/æ

**Comment by bebraw** [comment]
I set up a basic importer at https://github.com/antwarjs/ghost2antwar . You should be able to run the demo. cli hasn't been set up yet (I'll do that in a bit).

Further issues should go to that repo.
