### ISSUE TITLE
Getting Started: Image too big / text cut off

### ISSUE THREAD

**Issue by manonthemat** [antwarjs/antwar#101]
see screenshot for reference.

![fullscreen_11_17_15__11_25_am](https://cloud.githubusercontent.com/assets/5065940/11222251/501e3c9a-8d1e-11e5-8b47-bc0c56b17b8d.png)

Browser: Google Chrome

**Comment by bebraw** [comment]
This should be fixed now that there is a new site. Still some content bits to fix, though.
