### ISSUE TITLE
ETIMEDOUT getting started

### ISSUE THREAD

**Issue by sallespro** [antwarjs/antwar#119]
```
$ antwar --init antwar-site
2017.01.18.02.59.54 Start project initialization

2017.01.18.02.59.54 Fetching boilerplate metadata
2017.01.18.03.00.14
Project initialization failed Error: ETIMEDOUT
```

**Comment by bebraw** [comment]
Hi,

The cli has been deprecated and it won't be available in the future.

This generator is primarily for my own usage right now, but if you want to give it a go, run the repository examples. I've pushed some beta releases with the new logic. You need to mimic the demo projects then.

I'll close this issue once I complete the release. Thanks.

**Comment by bebraw** [comment]
A new version has been released. There's no CLI anymore and the setup is a little different (you have to write a file etc.). Let me know if you have any issues. Time to close.
