### ISSUE TITLE
Convert all of core to babel/es6 with babel-lint

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#12]
Currently it's CoffeeScript. Maybe start with a port to vanilla JS and then work from there.

**Comment by bebraw** [comment]
@eldh Any idea on `babel/es6` and `babel-lint`? They warn explicitly against usage in libraries at https://babeljs.io/docs/using-babel/ for require hook. In any case this would mean there would have to be some sort of build process and add some complexity to the project.

**Comment by eldh** [comment]
We could use babel-loader for selected files https://www.npmjs.com/package/babel-loader

**Comment by bebraw** [comment]
Yeah, it makes more sense on the frontend code. We could target `elements/` with that.

**Comment by bebraw** [comment]
Here's a nice approach: http://jlongster.com/Backend-Apps-with-Webpack--Part-I .

**Comment by bebraw** [comment]
Forgot to close this... This has been definitely done. There's Coffee at themes but that's a separate problem.
