### ISSUE TITLE
Site descriptions render unprocessed markdown

### ISSUE THREAD

**Issue by webdesserts** [antwarjs/antwar#121]
Right now it seems that the descriptions on the "index" pages of the site are rendering unprocessed markdown. The site could truncate the articles based on word count, but you would still need to deal with images, lists, and other html oddities. Rather than figuring out how to truncate these oddities, I would suggest that each article has a short description in the yaml metadata.

![screenshot](https://www.dropbox.com/s/t0wrsty9dt6ntl3/Screenshot%202017-03-27%2007.55.58.png?dl=1)

**Comment by bebraw** [comment]
Yeah, good idea. Either that or pushing the content through [remove-markdown](https://www.npmjs.com/package/remove-markdown) would do the trick.

**Comment by bebraw** [comment]
This should be fixed now. Just waiting GitHub pages to get out of maintenance mode.

**Comment by bebraw** [comment]
Ok, https://antwar.js.org/docs/ .
