### ISSUE TITLE
How to specify devtool for built JavaScript?

### ISSUE THREAD

**Issue by simon04** [antwarjs/antwar#123]
For debugging (such as https://github.com/webpack/webpack.js.org/issues/919) it would be helpful to get the source maps built via [devtool](https://webpack.js.org/configuration/devtool/). How can this be accomplished?

**Comment by bebraw** [comment]
Only interactive bits can receive source maps. You would have to use interactive config (env === `interactive`) to so that it sets `devtool` to the value you want. Source maps have been disabled on the site as the build is pretty slow even without them.

**Comment by bebraw** [comment]
I guess it's time to close this. There's not much I can do on Antwar side. More of a webpack problem.
