### ISSUE TITLE
Relative Links in Development vs. Production

### ISSUE THREAD

**Issue by skipjack** [antwarjs/antwar#125]
From webpack/webpack.js.org#1087...

It seems in production on webpack.js.org a trailing slash is added which doesn't exist in development. This causes relative urls like `./writers-guide` to work in development but fail in production leading to some confusion.

Production: `https://webpack.js.org/support/`
Development: `https://webpack.js.org/support`

**Comment by bebraw** [comment]
The trailing slash has to do with the fact that it actually generates something like `support/index.html` by design. I think I have to force the router to use trailing slashes always somehow.

Note that Antwar is using react-router 4 now (updated today).

**Comment by bebraw** [comment]
Can you try the dev version? Now I force everything to have a trailing slash so it's at least consistent. The error handling could be far better as now it's just a console message. That needs something better.

**Comment by skipjack** [comment]
Did you bump the antwar version on webpack.js.org already? If so, I'd be happy to test.

> The error handling could be far better as now it's just a console message. That needs something better.

The error handling for what?

**Comment by bebraw** [comment]
I haven't bumped the version yet as it's a bigger change (needs update to webpack 2 while at it).

Error handling as in accessing invalid url. It still renders something and you get a message in the console. Likely that needs a nice error message page instead but that's an easy problem.

**Comment by skipjack** [comment]
Ok, yeah I'd be happy to create a nice 404 page at some point.
