### ISSUE TITLE
Bundle scripts with pages/posts (isomorphic style)

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#16]
We'll want to use lazy loading (see https://github.com/rackt/react-router/tree/master/examples/partial-app-loading) here. Ie. we generate an index and a fragment for each page. Index will work as an entry point. After a client hits an index initially, it will consume those fragments after that. Thanks to Webpack's magic, we should get the needed bundles quite easily.

**Comment by gregvenech** [comment]
Is there a recommended way/workaround to include scripts currently?

**Comment by bebraw** [comment]
Not yet. I have to rework the way it handles page templates. I've been a bit busy with client work lately.

**Comment by bebraw** [comment]
Given there's `<Interactive>` now, closing this. It's not isomorphic, but still enough for tons of cases. If we want true isomorphism, that would need a different approach (and bigger bundles).
