### ISSUE TITLE
Support for directories in `posts` directory

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#17]
Ie. we should match against `**/*.md`. [glob](https://www.npmjs.com/package/glob) module is excellent for this purpose.

This will allow arbitrary layout for the directory. Note that there should be some way to define post ordering through configuration to make this sensible. Example:

**antwar.config.js**

```
module.exports = {
    sorting: function(a, b) {
         // see JS sort. both a and b contain regular post metadata after shaping through plugins
    },
};
```

**Comment by bebraw** [comment]
By the looks of it, maybe all we need to do is to enable recursive lookup for [require.context](http://webpack.github.io/docs/context.html#require-context) at `paths.js`.

Given we have a plugin system in place now, we could implement one to parse date from post metadata. Even url slugifying mechanism could be moved outside. What if we allowed the user to override whole `processPost` and provide some sensible defaults? That would be the most flexible option here.

**Comment by bebraw** [comment]
> Given we have a plugin system in place now, we could implement one to parse date from post metadata. Even url slugifying mechanism could be moved outside. What if we allowed the user to override whole processPost and provide some sensible defaults? That would be the most flexible option here.

Never mind. Just noticed that's possible already!

So I guess it might be just a matter of changing those flags.

**Comment by eldh** [comment]
Sounds good. Yeah, should be farily easy.
