### ISSUE TITLE
Provide browser based editor

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#3]
It might be nice to set up something browser based. Generally this is something that's lacking with static blogging tools.

The idea is that you would hit `antwar-editor` (or similar command). That would open up the blog in browser and show basic editing tools in some panel etc. You should be able to edit existing posts here, create new ones and publish drafts.

Technically speaking antwar would run a local server that would operate as a proxy between the user and the file system. It should be able to deal with git commits as well.

I think this sort of thing would bridge the gap between traditional blogging solutions (WordPress, Ghost) and static ones.

Later on this could be developed into a standalone service which you could access over web but that goes way beyond the scope of this issue.

**Comment by eldh** [comment]
I like the idea of having a browser based editor, but I think it should be developed as an add-on.

**Comment by bebraw** [comment]
Yeah. I'm not expecting something like this as a core feature. It is more about UX and polish.

**Comment by eldh** [comment]
Closing this here.
