### ISSUE TITLE
HMR is broken in the current build

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#33]
This probably got broken somewhere within CS -> JS conversion process. Just need to figure out what has changed and resolve.

**Comment by eldh** [comment]
*works for me*

**Comment by winkler1** [comment]
Me too

**Comment by bebraw** [comment]
We spent some time debugging this. The problem has to do with content. Changes made to it won't get caught by HMR due to the way it works. We'll likely need to rethink our approach a bit or try something rougher (full refresh on content modifications).
