### ISSUE TITLE
Error cannot find config

### ISSUE THREAD

**Issue by winkler1** [antwarjs/antwar#38]
Seems innocuous but having the first msg an error looks bad--

```
$ antwar --init rrocks_blog
{ [Error: Cannot find module '/Users/Jeff/repos/antwar.config.js'] code: 'MODULE_NOT_FOUND' }
Starting to initialize project
```

**Comment by bebraw** [comment]
Fixed. It was actually a cli related issue. Just needed to make sure it doesn't fail if it cannot find the default configuration file. If you update the cli to version `0.5.1` the error should go away.
