### ISSUE TITLE
Hook up `webpack-notifier`

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#43]
See https://www.npmjs.com/package/webpack-notifier . This should help us to give nicer output in case theme or something fails during development.

**Comment by bebraw** [comment]
I'm still a bit unsure whether or not this should go to the core. Maybe it's better to hook this up with the default boilerplate?

**Comment by eldh** [comment]
It could go in core with config option to toggle it on/off?

**Comment by bebraw** [comment]
Generally options are bad design. I would start by hooking it up with `boilerplate`. If it's actually useful, maybe we can move it to the core.

**Comment by eldh** [comment]
sounds good.

**Comment by bebraw** [comment]
Given it's possible to extend the configuration freely through site configuration now, this can be solved in user space.
