### ISSUE TITLE
Drop `coffee-loader` and `sass-loader` from core

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#44]
These can be pushed to themes now.

**Comment by eldh** [comment]
We need to consider site specific styles as well.

**Comment by bebraw** [comment]
> We need to consider site specific styles as well.

Good point. For that to work, it should be possible to set up site specific Webpack settings.

**Comment by bebraw** [comment]
Reopening this as we still have the dependencies around.

@eldh What's blocking this? I can't recall why we reverted the commit.

**Comment by eldh** [comment]
It was causing problems, don't remember exactly why/where. Should give it another shot.

**Comment by bebraw** [comment]
I managed to fix a couple of problems (didn't load theme config correctly, used from extension config). Now it yields a new error when enabled, though. See https://github.com/antwarjs/antwar/commit/0443c37e2f8a4178116f5a34990fb75c7ac935a9 .

Probably need to simplify this a lot till we have single external loader working and so on to gain a better understanding.

**Comment by bebraw** [comment]
In the end it was a lot of small, separate issues. Ie. theme config not loading correctly, extension config not loading, loading multiple loader config.

Esp. the last one is a little nasty. I wonder if we could detect this somehow (need to compare regex and see if they are the same against each theme loader regex).

**Comment by eldh** [comment]
Awesome!
