### ISSUE TITLE
Error when there are multiple items in assets

### ISSUE THREAD

**Issue by eldh** [antwarjs/antwar#59]
Got this error when I added another file to the root of the assets folder. Need further investigation.

```
/Users/eldh/Code/githubrepos/antwar/node_modules/async/lib/async.js:30
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
  at /Users/eldh/Code/githubrepos/antwar/node_modules/async/lib/async.js:30:31
  at /Users/eldh/Code/githubrepos/antwar/node_modules/async/lib/async.js:251:21
  at /Users/eldh/Code/githubrepos/antwar/node_modules/async/lib/async.js:575:34
  at cb (/Users/eldh/Code/githubrepos/antwar/node_modules/ncp/lib/ncp.js:255:37)
  at /Users/eldh/Code/githubrepos/antwar/node_modules/ncp/lib/ncp.js:108:16
  at /Users/eldh/Code/githubrepos/antwar/node_modules/ncp/lib/ncp.js:227:14
  at Object.oncomplete (fs.js:108:15)


```

**Comment by bebraw** [comment]
What does your assets structure look like? Do you have the site somewhere? Just trying to reproduce this.

**Comment by eldh** [comment]
I got the problem when I added favicon.png to `assets/`. It went away when I moved it to `assets/img/`. It happens when running antwar -b. Not sure if multiple things in root is actually the issue here, haven't tested that much more.

I pushed the site here: https://github.com/eldh/eldh.co.
