### ISSUE TITLE
Set up rough execution based tests

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#61]
We should run something like

```bash
npm i antwar-cli
antwar -i test
cd test
antwar -b
```

to make sure we don't get some weird crashes. This test could run against 0.10, 0.12 and io.js on Travis.

The script needs to be tweaked so that it links against the development version of core as the example I provided likely doesn't!

**Comment by eldh** [comment]
Got the actual test up but antwar is not showing up among my github organizations on travis...

**Comment by bebraw** [comment]
@eldh I set it up manually and got the org to show up. See https://travis-ci.org/antwarjs/antwar . There's also a badge now.

**Comment by bebraw** [comment]
Done, closing.
