### ISSUE TITLE
Rename `draft` as `isDraft`

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#67]
Rename draft as isDraft - reads better and communicates intention.

**Comment by eldh** [comment]
hm, should we allow the isDraft(s) flag on sections as well as specific posts? Thinking you either set it on the post (in headmaster or filename or something, depending on file), or by dropping it in a drafts folder. You might want to have several drafts folders if you have a more complex site.

**Comment by bebraw** [comment]
Interesting point. I wonder how the mapping should work with multiple draft folders. I suppose you can deal with it already by building a RegExp with some ors in it for Webpack to load the drafts to some section.

Having draft information within files themselves doesn't seem like a great idea as that hurts ux (how to tell normal content and drafts apart through fs).

This issue is more about our internal naming (paths.js, themes).
