### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by eldh** [antwarjs/antwar#8]
Fix some basic logo and branding stuff,

**Comment by eldh** [comment]
Had another idea for a logo mark. @bebraw What do you think? (disregard the color choice)


![screen shot 2015-03-14 at 23 21 19](https://cloud.githubusercontent.com/assets/612703/6653848/e5912d82-caa0-11e4-8e25-75934cbefba5.png)

**Comment by bebraw** [comment]
The first one looks good. I like the type. There's a little kerning issue around "w" but that's simple to fix. Just push it a little bit to the right and it will look better.

Considering homepage, maybe it would be good to arrange the elements like this:

```
<logo - the round thinger>

          ANTWAR

         <motto>
```

Motto is something we need to rethink. "A nice static site engine" doesn't tell much. But we can get back to that.

**Comment by eldh** [comment]
Closing this. We should think more about branding, but site looks ok for now.
