### ISSUE TITLE
Figure out safer ways to link inside the site

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#80]
Just doing hrefs is a bit dangerous if the target changes. We might want to figure out something safer (or go through current link components).

**Comment by iamstarkov** [comment]
sorry, I don’t follow, can you describe in a bit more details?

**Comment by bebraw** [comment]
Let's say you are linking from a blog post to another. If you do this the good old way (ie. just href) and the target changes somehow, it will get broken. Within the site itself we can provide safer links since we have all the routing information. In this case links would have to go through our logic (ie. some React component).

Alternatively or in addition we could implement some form of 404 checker that operates against the whole site. The advantage of this is that it would catch outbound links that are broken. I expect there are solutions for this already as it's a common problem. We could for instance provide some hook (pre-deployment?) that would perform the check.

**Comment by iamstarkov** [comment]
okie, I get it

**Comment by bebraw** [comment]
I think the right way to solve this is to use an external tool like [hyperlink](https://www.npmjs.com/package/hyperlink). No need to solve here.
