### ISSUE TITLE
Provide access to page metadata

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#83]
Looks like we could inject this through React. See https://github.com/nfl/react-helmet and https://github.com/kodyl/react-document-meta .

**Comment by iamstarkov** [comment]
But how are you going to extract metadata from posts?

**Comment by bebraw** [comment]
Currently it tries to parse `YAML headmatter` for Markdown posts should that exist. In addition we provide hooks. See [configuration docs](http://antwarjs.github.io/docs/configuration/). The configuration allows you to map content to specific urls, parse dates from them and so on.

If that is not enough you can inject custom data at `sort` hook. See [antwar.config.js of SurviveJS](https://github.com/survivejs/webpack_react/blob/master/antwar.config.js) for an example. So if options above don't work for you, you could for instance parse metadata per post from a separate JSON or so. You would just need some convention based on which to map it to a post (naming likely).

Based on the structure of [your site](https://github.com/iamstarkov/iamstarkov.github.io) it shouldn't be too difficult to port to Antwar. You would have to push your content to a directory and define a section mapping for it. If you want I can set up something simple for you to get started.

**Comment by iamstarkov** [comment]
> If you want I can set up something simple for you to get started.

ohh, thank you and nevermid, i can do it by myself when I will need it =)

**Comment by bebraw** [comment]
This isn't relevant anymore as pages go through EJS templating.
