### ISSUE TITLE
pre-rendering

### ISSUE THREAD

**Issue by iamstarkov** [antwarjs/antwar#86]
will antwar support pre-rendering the whole site?

**Comment by bebraw** [comment]
That's what we do now. It renders the whole site through `react-router` and you get static output. This is enough for simple sites without functionality relying on JavaScript. We're still missing proper JS support. Ideally you should be able to write bits you need in React while getting static output as well. There are plans but no implementation yet.

**Comment by iamstarkov** [comment]
thank you
