### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [antwarjs/antwar#9]
When you have a demo ready to show, please close the ticket and add to react.rocks, thanks!

**Comment by eldh** [comment]
For sure!

**Comment by bebraw** [comment]
@winkler1 Please see http://antwarjs.github.io/ .

Note that this is still quite alpha quality so a lot of features are missing. It might be a good idea to wait for the feature set to grow before going all PR on this.

**Comment by winkler1** [comment]
Cool thanks, will be trying this out! Is it ready for react.rocks, or would you rather I wait?

**Comment by bebraw** [comment]
@winkler1 Better wait still. Things are very much in flux. :)

**Comment by bebraw** [comment]
It's probably safe to close this now.

@winkler1 We probably should do react.rocks entry once we hit beta (goal - in two weeks).
