### ISSUE TITLE
PurifyCSS plugin

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#90]
It might be a nice idea to run [purifycss](https://github.com/purifycss/purifycss) against site content and CSS to get rid of unused CSS rules.

**Comment by eldh** [comment]
Would be awesome. Not sure which constraints it would put it on theme's, but could probably make it work.

**Comment by bebraw** [comment]
There's actually [purifycss-webpack-plugin](https://github.com/purifycss/purifycss-webpack-plugin) now. That helps a lot.

**Comment by bebraw** [comment]
webpack and the plugin I linked to can handle this. No need to do anything special in antwar.
