### ISSUE TITLE
Set up a favicon plugin

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwar#91]
It's probably smartest to inject favicon through a plugin. It can also use a JavaScript trick like covered at http://danlec.com/blog/stackoverflow-in-4096-bytes .

**Comment by eldh** [comment]
Yeah. We probably want to have it support all possible icons – iOS, windows tiles, android etc.

**Comment by bebraw** [comment]
Better leave this to webpack and associated plugins.
