### ISSUE TITLE
Missing theme error

### ISSUE THREAD

**Issue by RamonGebben** [antwarjs/antwar#96]
After reinstalling node_modules I started getting this error:

```
antwar -d
Start developing

Developing failed Error: Missing theme

Time elapsed: 36 ms
```
I'm very sure that the theme is in there. If you include the default-theme it doesn't work either.
Please fix this asap because I'm depending on this to work.

**Comment by bebraw** [comment]
There were two problems:

1. Configuration failed to be read correctly
2. `antwar-cli` chomped error when trying to read configuration

Now that we get an error, we can see that `{ [Error: Cannot find module 'antwar-highlight-plugin'] code: 'MODULE_NOT_FOUND' }`. Hit `npm i antwar-highlight-plugin -S` to fix this.

**Comment by RamonGebben** [comment]
Yes this helped a lot! Thanks!

**Comment by RamonGebben** [comment]
Yes this helped a lot! Thanks!
